import { Inter } from "next/font/google";
import "./globals.css";
import CustomLayout from "@/components/Layout";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("render RootLayout");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="bottom-center"
          reverseOrder={false}
          toastOptions={toastOptions}
          
        />
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  );
}

const toastOptions = {
  
  style: {
    background: "black",
    color: "white",
    borderRadius: "20px",
    success: {},
    error: {},
  },
};
