export const BulkEditArray = [
  {
    name: "Edit Prices",
    property: "price",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    isNumber: true,
    type: "single",
  },
  {
    name: "Edit Quantities",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    property: "quantity",
    isNumber: true,
    type: "single",
  },
  {
    name: "Edit Skus",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    property: "sku",
    type: "multible",
  },
  {
    name: "Edit barcodes",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    property: "barcode",
    type: "multible",
  },
  {
    name: "Edit Hs Codes",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    property: "hscode",
    type: "multible",
  },
  {
    name: "Edit weight",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    property: "weight",
    type: "single",
  },
  {
    name: "Add Images",
    property: "image",
    disabled: false,
    css: "text-[#333]",
    updateType: "modal",
    type: "single",
  },
  {
    name: "Remove Images",
    property: "image",
    disabled: false,
    css: "text-red-300",
    updateType: "delete",
  },
  {
    name: "Delete Varients",
    property: "varient",
    disabled: false,
    css: "text-[#333]",
    updateType: "delete",
    type: "single",
  },
  {
    name: "continue Selling when out of stock",
    disabled: false,
    css: "text-[#333]",
    property: "continue_out_stock",
    updateType: "singleAction",
    type: "single",
  },
  {
    name: "stop Selling When Out Of Stock",
    disabled: true,
    css: "text-[#333]",
    property: "continue_out_stock",
    updateType: "singleAction",
    value:true,
    type: "single",
  },
];
