import Image from "next/image";

export const data = {
  Keys: [
    "ID",
    "Title",
    "Price",
    "InventoryQuantity",
    "Color",
   
    "Size",
    "Length",
    "Images",
    "Color-Hex",
  ],

  values: [
    {
      ID: "1",
      Title: "Black, 14 - 16 Inches, 14",
      Price: "85.00",
      InventoryQuantity: 20,
      Color: "Black",
      Size: "14 - 16 Inches",
      Length: "14",
      Images: ["image1.jpg", "image2.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "2",
      Title: "Black, 14 - 16 Inches, 18",
      Price: "85.00",
      InventoryQuantity: 0,
      Color: "Black",
      Size: "14 - 16 Inches",
      Length: "18",
      Images: ["image3.jpg", "image4.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "3",
      Title: "Black, 14 - 16 Inches, 22",
      Price: "85.00",
      InventoryQuantity: 10,
      Color: "Black",
      Size: "14 - 16 Inches",
      Length: "22",
      Images: ["image5.jpg", "image6.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "4",
      Title: "Black, 18 - 20 Inches, 14",
      Price: "85.00",
      InventoryQuantity: 0,
      Color: "Black",
      Size: "18 - 20 Inches",
      Length: "14",
      Images: ["image7.jpg", "image8.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "5",
      Title: "Black, 18 - 20 Inches, 18",
      Price: "85.00",
      InventoryQuantity: 10,
      Color: "Black",
      Size: "18 - 20 Inches",
      Length: "18",
      Images: ["image9.jpg", "image10.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "6",
      Title: "Black, 18 - 20 Inches, 22",
      Price: "85.00",
      InventoryQuantity: 0,
      Color: "Black",
      Size: "18 - 20 Inches",
      Length: "22",
      Images: ["image11.jpg", "image12.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "7",
      Title: "Black, 22 - 24 Inches, 14",
      Price: "85.00",
      InventoryQuantity: 0,
      Color: "Black",
      Size: "22 - 24 Inches",
      Length: "14",
      Images: ["image13.jpg", "image14.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "8",
      Title: "Black, 22 - 24 Inches, 18",
      Price: "85.00",
      InventoryQuantity: 10,
      Color: "Black",
      Size: "22 - 24 Inches",
      Length: "18",
      Images: ["image15.jpg", "image16.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "9",
      Title: "Black, 22 - 24 Inches, 22",
      Price: "85.00",
      InventoryQuantity: 0,
      Color: "Black",
      Size: "22 - 24 Inches",
      Length: "22",
      Images: ["image17.jpg", "image18.jpg"],
      "Color-Hex": "#000000",
    },
    {
      ID: "10",
      Title: "Antik Pink, 14 - 16 Inches, 14",
      Price: "90.00",
      InventoryQuantity: 0,
      Color: "Antik Pink",
      Size: "14 - 16 Inches",
      Length: "14",
      Images: ["image19.jpg", "image20.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "11",
      Title: "Antik Pink, 14 - 16 Inches, 18",
      Price: "90.00",
      InventoryQuantity: 10,
      Color: "Antik Pink",
      Size: "14 - 16 Inches",
      Length: "18",
      Images: ["image21.jpg", "image22.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "12",
      Title: "Antik Pink, 14 - 16 Inches, 22",
      Price: "90.00",
      InventoryQuantity: 0,
      Color: "Antik Pink",
      Size: "14 - 16 Inches",
      Length: "22",
      Images: ["image23.jpg", "image24.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "13",
      Title: "Antik Pink, 18 - 20 Inches, 14",
      Price: "100.00",
      InventoryQuantity: 0,
      Color: "Antik Pink",
      Size: "18 - 20 Inches",
      Length: "14",
      Images: ["image25.jpg", "image26.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "14",
      Title: "Antik Pink, 18 - 20 Inches, 18",
      Price: "100.00",
      InventoryQuantity: 0,
      Color: "Antik Pink",
      Size: "18 - 20 Inches",
      Length: "18",
      Images: ["image27.jpg", "image28.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "15",
      Title: "Antik Pink, 18 - 20 Inches, 22",
      Price: "100.00",
      InventoryQuantity: 2,
      Color: "Antik Pink",
      Size: "18 - 20 Inches",
      Length: "22",
      Images: ["image29.jpg", "image30.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "16",
      Title: "Antik Pink, 22 - 24 Inches, 14",
      Price: "100.00",
      InventoryQuantity: 2,
      Color: "Antik Pink",
      Size: "22 - 24 Inches",
      Length: "14",
      Images: ["image31.jpg", "image32.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "17",
      Title: "Antik Pink, 22 - 24 Inches, 18",
      Price: "100.00",
      InventoryQuantity: 1,
      Color: "Antik Pink",
      Size: "22 - 24 Inches",
      Length: "18",
      Images: ["image33.jpg", "image34.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "18",
      Title: "Antik Pink, 22 - 24 Inches, 22",
      Price: "100.00",
      InventoryQuantity: 0,
      Color: "Antik Pink",
      Size: "22 - 24 Inches",
      Length: "22",
      Images: ["image35.jpg", "image36.jpg"],
      "Color-Hex": "#FF69B4",
    },
    {
      ID: "19",
      Title: "Coral, 14 - 16 Inches, 14",
      Price: "105.00",
      InventoryQuantity: 0,
      Color: "Coral",
      Size: "14 - 16 Inches",
      Length: "14",
      Images: ["image37.jpg", "image38.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "20",
      Title: "Coral, 14 - 16 Inches, 18",
      Price: "105.00",
      InventoryQuantity: 2,
      Color: "Coral",
      Size: "14 - 16 Inches",
      Length: "18",
      Images: ["image39.jpg", "image40.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "21",
      Title: "Coral, 14 - 16 Inches, 22",
      Price: "105.00",
      InventoryQuantity: 3,
      Color: "Coral",
      Size: "14 - 16 Inches",
      Length: "22",
      Images: ["image41.jpg", "image42.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "22",
      Title: "Coral, 18 - 20 Inches, 14",
      Price: "105.00",
      InventoryQuantity: 0,
      Color: "Coral",
      Size: "18 - 20 Inches",
      Length: "14",
      Images: ["image43.jpg", "image44.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "23",
      Title: "Coral, 18 - 20 Inches, 18",
      Price: "105.00",
      InventoryQuantity: 0,
      Color: "Coral",
      Size: "18 - 20 Inches",
      Length: "18",
      Images: ["image45.jpg", "image46.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "24",
      Title: "Coral, 18 - 20 Inches, 22",
      Price: "105.00",
      InventoryQuantity: 4,
      Color: "Coral",
      Size: "18 - 20 Inches",
      Length: "22",
      Images: ["image47.jpg", "image48.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "25",
      Title: "Coral, 22 - 24 Inches, 14",
      Price: "105.00",
      InventoryQuantity: 2,
      Color: "Coral",
      Size: "22 - 24 Inches",
      Length: "14",
      Images: ["image49.jpg", "image50.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "26",
      Title: "Coral, 22 - 24 Inches, 18",
      Price: "105.00",
      InventoryQuantity: 2,
      Color: "Coral",
      Size: "22 - 24 Inches",
      Length: "18",
      Images: ["image51.jpg", "image52.jpg"],
      "Color-Hex": "#FF7F50",
    },
    {
      ID: "27",
      Title: "Coral, 22 - 24 Inches, 22",
      Price: "105.00",
      InventoryQuantity: 8,
      Color: "Coral",
      Size: "22 - 24 Inches",
      Length: "22",
      Images: ["image53.jpg", "image54.jpg"],
      "Color-Hex": "#FF7F50",
    },
  ],
  customHeader: { InventoryQuantity: () => <span>Inventory Quantity</span> },
  customColumn: {
    theFirst: [
      {name: 'name Or Key_1',
        key:"nameOrKeyFirst_1",
        value: ({ item }) => <div>{item ? item : "nameOrKey_1"}</div>,},
      {name: 'name Or Key_2',
        key:"nameOrKeyFirst_2",
        value: ({ item }) => <div>{item ? item : "nameOrKey_12"}</div>},
    ],
    Images: ({ item }) => (
      <div className="w-full flex justify-center">
        <Image src={`/logo.png`} alt={item} width={50} height={50} />
      </div>
    ),
    theLast:  [
      {name: 'name Or Key_1',
        key:"nameOrKeyLast_1",
        value: ({ item }) => <div>{item ? item : "nameOrKey_1"}</div>,},
      {name: 'name Or Key_2',
        key:"nameOrKeyLast_2",
        value: ({ item }) => <div>{item ? item : "nameOrKey_12"}</div>},
    ],
  },
  customRow: ({ itemRow }) =>
    typeof itemRow === "object" && Object.values(itemRow)?.length > 0
      ? Object.entries(itemRow).map(([key, value], index) => {
          if (data?.customColumn?.[key]) {
            let CustomComponent = data?.customColumn[key];
            return (
              <td
                key={key + value[0]}
                className={`whitespace-nowrap px-3 py-2 font-medium text-gray-600 bg-transparent text-center`}
              >
                <CustomComponent item={value[0]} />
              </td>
            );
          }
          return <td key={index}>{value}</td>;
        })
      : null,
};

export const variants = [
  {
    isColor: "",
    key_ar: "sizes",
    key_en: "sizes",
    values: [
      {
        value_ar: "xl",
        value_en: "xl",
        color: "",
      },
      {
        value_ar: "xxl",
        value_en: "xxl",
        color: "",
      },
      {
        value_ar: "lg",
        value_en: "lg",
        color: "",
      },
      {
        value_ar: "md",
        value_en: "md",
        color: "",
      },
    ],
    edit: false,
  },
  {
    isColor: "",
    key_ar: "Ahmed",
    key_en: "Ahmed",
    values: [
      {
        value_ar: "sizes",
        value_en: "sizes",
        color: "",
      },
    ],
    edit: false,
  },
  {
    isColor: "",
    key_ar: "colors",
    key_en: "colors",
    values: [
      {
        value_ar: "red",
        value_en: "red",
        color: "",
      },
      {
        value_ar: "blue",
        value_en: "blue",
        color: "",
      },
      {
        value_ar: "dsadsadsaadsdsadsa",
        value_en: "yellow",
        color: "",
      },
    ],
    edit: false,
  },
];

export const dataVariants = {
  product: {
    id: "123456789",
    title: "Sample Product",
    description: "This is a sample product description.",
    price: "99",
    variants: [
      {
        id: "1",
        title: "Black, 14 - 16 Inches, 14",
        price: "85.00",
        inventory_quantity: 20,
        inventories: [
          {
            name: "cairo",
            price:20,
            quantity: {
              Available: 10,
              Committed: 0,
              On_hand: 0,
              Unavailable: {
                Damaged: 3,
                Quality_control: 2,
                Safety_stock: 3,
                Other: 0,
                total: 8,
              },
            },
          },
          {
            name: "nasr city",
            price:20,
            quantity: {
              Available: 10,
              Committed: 0,
              On_hand: 0,
              Unavailable: {
                Damaged: 3,
                Quality_control: 2,
                Safety_stock: 3,
                Other: 0,
                total: 8,
              },
            },
          },
        ],
        options: {
          color: "Black",
          size: "14 - 16 Inches",
          length: "14",
        },
        images: ["image1.jpg", "image2.jpg"],
        color_hex: "#000000",
      },
      {
        id: "2",
        title: "Black, 14 - 16 Inches, 18",
        price: "85.00",
        inventory_quantity: 0,
        options: {
          color: "Black",
          size: "14 - 16 Inches",
          length: "18",
        },
        images: ["image3.jpg", "image4.jpg"],
        color_hex: "#000000",
      },
      {
        id: "3",
        title: "Black, 14 - 16 Inches, 22",
        price: "85.00",
        inventory_quantity: 10,
        options: {
          color: "Black",
          size: "14 - 16 Inches",
          length: "22",
        },
        images: ["image5.jpg", "image6.jpg"],
        color_hex: "#000000",
      },
      {
        id: "4",
        title: "Black, 18 - 20 Inches, 14",
        price: "85.00",
        inventory_quantity: 0,
        options: {
          color: "Black",
          size: "18 - 20 Inches",
          length: "14",
        },
        images: ["image7.jpg", "image8.jpg"],
        color_hex: "#000000",
      },
      {
        id: "5",
        title: "Black, 18 - 20 Inches, 18",
        price: "85.00",
        inventory_quantity: 10,
        options: {
          color: "Black",
          size: "18 - 20 Inches",
          length: "18",
        },
        images: ["image9.jpg", "image10.jpg"],
        color_hex: "#000000",
      },
      {
        id: "6",
        title: "Black, 18 - 20 Inches, 22",
        price: "85.00",
        inventory_quantity: 0,
        options: {
          color: "Black",
          size: "18 - 20 Inches",
          length: "22",
        },
        images: ["image11.jpg", "image12.jpg"],
        color_hex: "#000000",
      },
      {
        id: "7",
        title: "Black, 22 - 24 Inches, 14",
        price: "85.00",
        inventory_quantity: 0,
        options: {
          color: "Black",
          size: "22 - 24 Inches",
          length: "14",
        },
        images: ["image13.jpg", "image14.jpg"],
        color_hex: "#000000",
      },
      {
        id: "8",
        title: "Black, 22 - 24 Inches, 18",
        price: "85.00",
        inventory_quantity: 10,
        options: {
          color: "Black",
          size: "22 - 24 Inches",
          length: "18",
        },
        images: ["image15.jpg", "image16.jpg"],
        color_hex: "#000000",
      },
      {
        id: "9",
        title: "Black, 22 - 24 Inches, 22",
        price: "85.00",
        inventory_quantity: 0,
        options: {
          color: "Black",
          size: "22 - 24 Inches",
          length: "22",
        },
        images: ["image17.jpg", "image18.jpg"],
        color_hex: "#000000",
      },
      {
        id: "10",
        title: "Antik Pink, 14 - 16 Inches, 14",
        price: "90.00",
        inventory_quantity: 0,
        options: {
          color: "Antik Pink",
          size: "14 - 16 Inches",
          length: "14",
        },
        images: ["image19.jpg", "image20.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "11",
        title: "Antik Pink, 14 - 16 Inches, 18",
        price: "90.00",
        inventory_quantity: 10,
        options: {
          color: "Antik Pink",
          size: "14 - 16 Inches",
          length: "18",
        },
        images: ["image21.jpg", "image22.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "12",
        title: "Antik Pink, 14 - 16 Inches, 22",
        price: "90.00",
        inventory_quantity: 0,
        options: {
          color: "Antik Pink",
          size: "14 - 16 Inches",
          length: "22",
        },
        images: ["image23.jpg", "image24.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "13",
        title: "Antik Pink, 18 - 20 Inches, 14",
        price: "100.00",
        inventory_quantity: 0,
        options: {
          color: "Antik Pink",
          size: "18 - 20 Inches",
          length: "14",
        },
        images: ["image25.jpg", "image26.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "14",
        title: "Antik Pink, 18 - 20 Inches, 18",
        price: "100.00",
        inventory_quantity: 0,
        options: {
          color: "Antik Pink",
          size: "18 - 20 Inches",
          length: "18",
        },
        images: ["image27.jpg", "image28.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "15",
        title: "Antik Pink, 18 - 20 Inches, 22",
        price: "100.00",
        inventory_quantity: 2,
        options: {
          color: "Antik Pink",
          size: "18 - 20 Inches",
          length: "22",
        },
        images: ["image29.jpg", "image30.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "16",
        title: "Antik Pink, 22 - 24 Inches, 14",
        price: "100.00",
        inventory_quantity: 2,
        options: {
          color: "Antik Pink",
          size: "22 - 24 Inches",
          length: "14",
        },
        images: ["image31.jpg", "image32.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "17",
        title: "Antik Pink, 22 - 24 Inches, 18",
        price: "100.00",
        inventory_quantity: 1,
        options: {
          color: "Antik Pink",
          size: "22 - 24 Inches",
          length: "18",
        },
        images: ["image33.jpg", "image34.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "18",
        title: "Antik Pink, 22 - 24 Inches, 22",
        price: "100.00",
        inventory_quantity: 0,
        options: {
          color: "Antik Pink",
          size: "22 - 24 Inches",
          length: "22",
        },
        images: ["image35.jpg", "image36.jpg"],
        color_hex: "#FF69B4",
      },
      {
        id: "19",
        title: "Coral, 14 - 16 Inches, 14",
        price: "105.00",
        inventory_quantity: 0,
        options: {
          color: "Coral",
          size: "14 - 16 Inches",
          length: "14",
        },
        images: ["image37.jpg", "image38.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "20",
        title: "Coral, 14 - 16 Inches, 18",
        price: "105.00",
        inventory_quantity: 2,
        options: {
          color: "Coral",
          size: "14 - 16 Inches",
          length: "18",
        },
        images: ["image39.jpg", "image40.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "21",
        title: "Coral, 14 - 16 Inches, 22",
        price: "105.00",
        inventory_quantity: 3,
        options: {
          color: "Coral",
          size: "14 - 16 Inches",
          length: "22",
        },
        images: ["image41.jpg", "image42.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "22",
        title: "Coral, 18 - 20 Inches, 14",
        price: "105.00",
        inventory_quantity: 0,
        options: {
          color: "Coral",
          size: "18 - 20 Inches",
          length: "14",
        },
        images: ["image43.jpg", "image44.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "23",
        title: "Coral, 18 - 20 Inches, 18",
        price: "105.00",
        inventory_quantity: 0,
        options: {
          color: "Coral",
          size: "18 - 20 Inches",
          length: "18",
        },
        images: ["image45.jpg", "image46.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "24",
        title: "Coral, 18 - 20 Inches, 22",
        price: "105.00",
        inventory_quantity: 4,
        options: {
          color: "Coral",
          size: "18 - 20 Inches",
          length: "22",
        },
        images: ["image47.jpg", "image48.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "25",
        title: "Coral, 22 - 24 Inches, 14",
        price: "105.00",
        inventory_quantity: 2,
        options: {
          color: "Coral",
          size: "22 - 24 Inches",
          length: "14",
        },
        images: ["image49.jpg", "image50.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "26",
        title: "Coral, 22 - 24 Inches, 18",
        price: "105.00",
        inventory_quantity: 2,
        options: {
          color: "Coral",
          size: "22 - 24 Inches",
          length: "18",
        },
        images: ["image51.jpg", "image52.jpg"],
        color_hex: "#FF7F50",
      },
      {
        id: "27",
        title: "Coral, 22 - 24 Inches, 22",
        price: "105.00",
        inventory_quantity: 8,
        options: {
          color: "Coral",
          size: "22 - 24 Inches",
          length: "22",
        },
        images: ["image53.jpg", "image54.jpg"],
        color_hex: "#FF7F50",
      },
    ],
    options: [
      {
        name: "Color",
        values: ["Black", "Antik Pink", "Coral"],
      },
      {
        name: "Size",
        values: ["14 - 16 Inches", "18 - 20 Inches", "22 - 24 Inches"],
      },
      {
        name: "Length",
        values: ["14", "18", "22"],
      },
    ],
  },
};
